---
title: "Data Products Week4 Assignment"
author: "Raja"
date: "28 January 2018"
output:
  slidy_presentation: default
  ioslides_presentation: default
runtime: shiny
---

## Indian 2009 2014 Elections Voting % Shiny Project

- The project represents 2009 2014 Lok Sabha election 
- Data for State wise election poll % is got from www.data.gov.in
- Data for Lat Long of the Indian state capitals are got from www.mapmyindia.com
- The data is represented in a shiny application and interactive India map


## How the shiny app is built

- There is a sidebarlayout with a sidebarpanel and mainpanel
- The sidebarpanel has a list of Indian/State Union Territory Capitals as Radiobuttons
- The data for the radio button for the State/UT & capitals are loaded from the downloaded csv file
- On selection of the particular State UT in the radio button the appropriate state/UT voting % is populated as a comparitive histogram against the lat/long location of the State/UT in the Indian Map

## How the application works

- click on the slidebar panel with title panel 2009 2014 Lok Sabha Elections Voting % Comparison
- Click on the radio button you want to see the relative comparison of the voting % of the state/UT
- The shiny application is interspersed with a leaflet map and the mainpanel is shown as a leaflet map
- Once the particular radio button is selected the shiny server throws up the comparitive histogram in the Indian map against the State/UT capital(triangulated by lat/long) as a leaflet minichart
- setView is used to give the focus on the particular State/UT capital and show the comparitive histogram in 2 different colors
- URL to the application: https://rajajayaram.shinyapps.io/DPWeek4Assignment/

## The 2009 2014 Lok Sabha Voting % Comparison Shiny UI

```{r,echo=FALSE}

df=read.csv2("Statewise polling Datacsv.csv",header=TRUE,sep=",")

content<-paste(df[1]$State.UT,df[2]$Capital)
newframe<-data.frame(lat=as.numeric(levels(df$Lat))[df$Lat],lng=as.numeric(levels(df$Long))[df$Long])
chartframe<-data.frame(as.numeric(levels(df$Percentage.of.votes.polled.2009))[df$Percentage.of.votes.polled.2009],as.numeric(levels(df$Percentage.of.votes.polled.2014))[df$Percentage.of.votes.polled.2014])
colnames(chartframe)<-c("2009 Voting %","2014 Voting %")
Polldata<-data.frame(df$State.UT,df$Percentage.of.votes.polled.2009,df$Percentage.of.votes.polled.2014)
combiframe<-paste(Polldata$df.State.UT,Polldata$df.Percentage.of.votes.polled.2009)
combiframe<-paste(combiframe,Polldata$df.Percentage.of.votes.polled.2014)

print("State Wise 2009 and 2014 Polling %")
print("State 2009% 2014%")
print("===============")
for (i in 1:length(content))
    {
      print(combiframe[i])
    }
```